-- INSERT STATEMENTS

USE OnShop1939213;
GO

INSERT INTO 
	dbo.product_category(category_name, parent_id)
VALUES
	('Baby, Child & Toys', NULL),
	('Fruits & Vegetables', NULL),
	('Meat & Seafood', NULL),
	('Dairy, Chilled & Eggs', NULL),
	('Frozen', NULL),
	('Food Cupboard', NULL),
	('Rice, Noodles & Cooking Ingredients', NULL),
	('Drinks', NULL),
	('Beer, Wine & Spirits', NULL),
	('Health & Beauty', NULL),
	('Household', NULL),
	('Electrical, Lifestyle & Pets', NULL),
	('Fruits', 2),
	('Vegetables', 2),
	('Chicken', 3),
	('Pork', 3),
	('Beef & Lamb', 3),
	('Fish & Seafood', 3),
	('Meatballs', 3),
	('Eggs', 4),
	('Fresh Milk', 4),
	('UHT Milk', 4),
	('Cheese', 4),
	('Butter, Margarine & Spreads', 4),
	('Cream', 4),
	('Yoghurt', 4),
	('Delicatessen', 4),
	('Chilled Food', 4),
	('Chilled Beverages', 4),
	('Chilled Desserts', 4),
	('Ice Cream', 4),
	('Ice Cream', 5),
	('Frozen Desserts', 5),
	('Frozen Greens', 5),
	('Frozen Food', 5),
	('Frozen Meat', 5),
	('Frozen Seafood', 5),
	('Breakfast', 6),
	('Breads', 6),
	('Breakfast Spreads', 6),
	('Chocolates', 6),
	('Sweets', 6),
	('Snacks', 6),
	('Biscuits', 6),
	('Canned Food', 6),
	('Ready-to-Eat', 6),
	('Baking Needs', 7),
	('Rice', 7),
	('Noodles', 7),
	('Pasta', 7),
	('Sugar & Sweeteners', 7),
	('Oil', 7),
	('Cooking Paste & Sauces', 7),
	('Condiments', 7),
	('Seasonings', 7),
	('Soups', 7),
	('Dried Food', 7),
	('Coffee', 8),
	('Tea', 8),
	('Juices', 8),
	('Beverages', 8),
	('UHT Milk', 8),
	('Water', 8),
	('Beer', 9),
	('Wine', 9),
	('Spirits', 9),
	('Drinking Accessories', 9),
	('Tonics & Supplements', 10),
	('Hair', 10),
	('Face', 10),
	('Mouth', 10),
	('Body', 10),
	('Hand & Foot Care', 10),
	('Makeup', 10),
	('Sanitary', 10),
	('Adult Hygiene', 10),
	('Family Planning', 10),
	('Medicine & First Aid', 10),
	('Beauty Appliances', 10),
	('Laundry Care', 11),
	('Detergents', 11),
	('Dishwashing', 11),
	('Home Cleaners', 11),
	('Fresheners', 11),
	('Pest Control', 11),
	('Paper & Tissue', 11),
	('Kitchen & Dining', 11),
	('Home Needs', 11),
	('Stationery & Batteries', 11),
	('Party Needs & Disposables', 12),
	('Electronics', 12),
	('Home Appliances', 12),
	('Entertainment', 12),
	('Automotive', 12),
	('Lighting', 12),
	('Outdoor', 12),
	('Pets', 12),
	('Apples & Pears', 13),
	('Berries & Cherries', 13),
	('Kiwi & Grapes', 13),
	('Citrus Fruits', 13),
	('Stone Fruits', 13),
	('Tropical Fruits', 13),
	('Frozen Fruits', 13),
	('Asparagus & Sprouts', 14),
	('Beans, Peas & Nuts', 14),
	('Broccoli & Cauliflowers', 14),
	('Carrots, Potatoes & Roots', 14),
	('Cucumbers & Lady Fingers', 14),
	('Cabbages, Celeries & Lettuces', 14),
	('Chillies & Capsicums', 14),
	('Garlic, Ginger & Onions', 14),
	('Brinjals, Gourds & Squashes', 14),
	('Leafy Vegetables', 14),
	('Mushrooms', 14),
	('Spices & Herbs', 14),
	('Tomatoes & Corn', 14),
	('Frozen Vegetables', 14),
	('Fresh Chicken', 15),
	('Frozen Chicken', 15),
	('Fresh Pork', 16),
	('Frozen Pork', 16),
	('Frozen Beef & Lamb', 17),
	('Fresh Fish & Seafood', 18),
	('Frozen Fish', 18),
	('Frozen Breaded Seafood', 18),
	('Frozen Crabs & Prawns', 18),
	('Frozen Crab Sticks & Fish Balls', 18),
	('Frozen Shellfish & Others', 18),
	('Chilled Fish Balls & Fish Cakes', 18),
	('Smoked Salmon', 18),
	('Beef Meatball', 19),
	('Chicken Meatball', 19),
	('Pork Meatball', 19),
	('Fresh Eggs', 20),
	('Preserved Eggs', 20),
	('Fresh Milk', 21),
	('Soy Milk', 21),
	('Flavoured Milk', 21),
	('Cultured Milk', 21),
	('UHT Milk', 22),
	('Soy UHT Milk', 22),
	('Flavoured UHT Milk', 22),
	('Cheese Blocks', 23),
	('Cheese Spreads', 23),
	('Sliced Cheese', 23),
	('Shredded & Grated Cheese', 23),
	('Natural Cheese', 23),
	('Butter', 24),
	('Margarine & Spreads', 24),
	('Whipping Creams', 25),
	('Cooking & Thickened Creams', 25),
	('Greek Yoghurt', 26),
	('Natural Yoghurt', 26),
	('Flavoured Yoghurt', 26),
	('Yoghurt Drinks', 26),
	('Ham & Salami', 27),
	('Roasted Meat', 27),
	('Sausages & Bacon', 27),
	('Fish Balls & Fish Cakes', 28),
	('Meat Balls', 28),
	('Beancurd & Tofu', 28),
	('Kimchi', 28),
	('Noodles, Rice Cake & Pasta', 28),
	('Smoked Salmon', 28),
	('Juices', 29),
	('Cultured Milk', 29),
	('Yoghurt Drinks', 29),
	('Puddings & Jellies', 30),
	('Ice Cream Tubs', 31),
	('Ice Cream Packs', 31),
	('Frozen Yoghurt', 31),
	('Ice Cream Tubs', 32),
	('Ice Cream Packs', 32),
	('Frozen Yoghurt', 32),
	('Frozen Cakes', 33),
	('Other Desserts', 33),
	('Frozen Fruits', 34),
	('Frozen Vegetables', 34),
	('Breads, Buns & Prata', 35),
	('Burger Patties', 35),
	('Chicken Delights', 35),
	('Dim Sum', 35),
	('Dumplings & Gyoza', 35),
	('Fries', 35),
	('Hash Browns & Wedges', 35),
	('Local Delights', 35),
	('Nuggets', 35),
	('Otah & Satay', 35),
	('Pies & Pizza', 35),
	('Ready Meals', 35),
	('Frozen Beef & Lamb', 36),
	('Frozen Chicken', 36),
	('Frozen Pork', 36),
	('Franks & Sausages', 36),
	('Meatballs & Others', 36),
	('Frozen Breaded Seafood', 37),
	('Frozen Crabs & Prawns', 37),
	('Frozen Crab Sticks & Fish Balls', 37),
	('Frozen Fish', 37),
	('Frozen Shellfish & Others', 37),
	('Adult Cereals', 38),
	('Kids Cereals', 38),
	('Granola, Muesli & Oats', 38),
	('Instant Cereals', 38),
	('Cereal Bars', 38),
	('Protein Bars', 38),
	('Pancake Mix', 38),
	('Flatbreads & Wraps', 39),
	('Sandwich & Sliced', 39),
	('Buns & Rolls', 39),
	('Cakes & Pies', 39),
	('Chocolate & Cocoa', 40),
	('Peanut Butter & Nut Spread', 40),
	('Jam', 40),
	('Kaya', 40),
	('Honey', 40),
	('Maple Syrup', 40),
	('Savoury Spread', 40),
	('Chocolate Bars & Blocks', 41),
	('Chocolate Boxes & Gifts', 41),
	('Chocolate Pouches', 41),
	('Multi Pack Chocolates', 41),
	('Assorted Chocolates', 41),
	('Assorted Candies', 42),
	('Gummies & Pastilles', 42),
	('Soft & Chewy Candy', 42),
	('Mints & Lozenges', 42),
	('Lollipops & Hard Candy', 42),
	('Marshmallow & Nougat', 42),
	('Chips, Crisps & Sticks', 43),
	('Corn Chips & Tortillas', 43),
	('Rice Crackers', 43),
	('Dried & Preserved Fruits', 43),
	('Jellies & Puddings', 43),
	('Nuts & Seeds', 43),
	('Seaweed & Floss', 43),
	('Other Snacks', 43),
	('Savoury Snacks', 43),
	('Dips', 43),
	('Assorted Biscuits', 44),
	('Pretzels & Biscuit Sticks', 44),
	('Chocolate Cookies', 44),
	('Butter Cookies', 44),
	('Oat Biscuits', 44),
	('Other Cookies', 44),
	('Crackers', 44),
	('Creamed & Filled', 44),
	('Digestive & Marie', 44),
	('Wafers', 44),
	('Canned Beans', 45),
	('Canned Vegetables', 45),
	('Canned Fruits & Desserts', 45),
	('Canned Abalone', 45),
	('Canned Meat', 45),
	('Canned Sardines & Mackerels', 45),
	('Canned Tuna & Salmon', 45),
	('Other Canned Seafood', 45),
	('Instant Rice', 46),
	('Instant Porridge', 46),
	('Instant Meals', 46),
	('Instant Noodles', 46),
	('Instant Cups', 46),
	('Instant Pasta', 46),
	('Instant Soups', 46),
	('Instant Desserts', 46),
	('Popcorn', 46),
	('Baking Flour & Mix', 47),
	('Breadcrumbs', 47),
	('Jelly Powder & Mix', 47),
	('Coconut Products', 47),
	('Other Baking Needs', 47),
	('Black, Brown & Red Rice', 48),
	('Japanese Rice', 48),
	('White Rice', 48),
	('Multi Grains & Quinoa', 48),
	('Glutinous Rice', 48),
	('Cooking Noodles', 49),
	('Fresh & Chilled Noodles', 49),
	('Instant Cups', 49),
	('Instant Noodles', 49),
	('Vermicelli', 49),
	('Spaghetti & Linguine', 50),
	('Macaroni & Shells', 50),
	('Fusilli & Spirals', 50),
	('Penne', 50),
	('Farfalle & Shapes', 50),
	('Lasagna Sheets', 50),
	('Instant Pasta', 50),
	('Granulated Sugar', 51),
	('Icing & Caster Sugar', 51),
	('Raw & Brown Sugar', 51),
	('Sugar Cubes, Sticks & Crystals', 51),
	('Sweeteners', 51),
	('Creamers', 51),
	('Cooking Oil', 52),
	('Canola Oil', 52),
	('Corn & Soya Bean Oil', 52),
	('Olive Oil', 52),
	('Sunflower Oil', 52),
	('Vegetable Oil', 52),
	('Coconut Oil', 52),
	('Grapeseed Oil', 52),
	('Specialty Oil', 52),
	('Sesame Oil', 52),
	('Cooking Paste', 53),
	('Chili Paste & Sambal', 53),
	('Pasta Sauces', 53),
	('Pesto', 53),
	('Soybean Paste', 53),
	('Tomato Paste & Puree', 53),
	('Fish Sauce', 54),
	('Oyster & Abalone Sauce', 54),
	('Cooking Wine & Vinegar', 54),
	('Light Soy Sauce', 54),
	('Dark Soy Sauce', 54),
	('Tomato Sauce', 54),
	('Chili Sauce', 54),
	('BBQ & Teriyaki Sauce', 54),
	('Mustard', 54),
	('Mayonnaise', 54),
	('Salad Dressing', 54),
	('Chutney & Relish', 54),
	('Herbs', 55),
	('Spices', 55),
	('Salt', 55),
	('Seasoning', 55),
	('Sesame Oil', 55),
	('Broths & Stocks', 56),
	('Canned & Tetra Soups', 56),
	('Instant Bases', 56),
	('Beans, Seeds & Nuts', 57),
	('Chinese Herbs & Others', 57),
	('3-in-1 Coffee', 58),
	('Capsules & Pods', 58),
	('Ground Coffee & Beans', 58),
	('Instant Coffee', 58),
	('Ice Coffee', 58),
	('Condensed Milk & Creamers', 58),
	('Coffee Filters', 58),
	('Coffee Machines', 58),
	('Black Tea', 59),
	('Green Tea', 59),
	('Fruit, Flower & Herbal', 59),
	('Ice Tea', 59),
	('Milk Tea', 59),
	('Chilled Juice', 60),
	('Apple Juice', 60),
	('Orange Juice', 60),
	('Berry Juice', 60),
	('Cranberry & Pomegranate juice', 60),
	('Grape Juice', 60),
	('Lemon & Lime Juice', 60),
	('Tomato & Vegetable Juice', 60),
	('Tropical Juice', 60),
	('Mixed Juice', 60),
	('Coconut Water', 60),
	('Carton Drinks', 61),
	('Adult Milk Powder', 61),
	('Asian Drinks', 61),
	('Carbonated Drinks', 61),
	('Chocolate & Malted', 61),
	('Cider & Drinking Vinegar', 61),
	('Coconut Water', 61),
	('Cordials & Syrups', 61),
	('Energy & Isotonic Drinks', 61),
	('UHT Milk', 62),
	('Soy UHT Milk', 62),
	('Flavoured UHT Milk', 62),
	('Alkaline Water', 63),
	('Mineral Water', 63),
	('Still Water', 63),
	('Cooling Water', 63),
	('Flavoured Water', 63),
	('Sparkling Water', 63),
	('Alcopop & Cider', 64),
	('Ale, Lager & Malt', 64),
	('Dark Beer & Stout', 64),
	('Fruit Beer & Shandy', 64),
	('Premium Beer', 64),
	('White Wine', 65),
	('Red Wine', 65),
	('Rose Wine', 65),
	('Champagne', 65),
	('Sparkling Wine', 65),
	('Dessert Wine', 65),
	('Argentina', 65),
	('Australia', 65),
	('Canada', 65),
	('Chile', 65),
	('Chinese', 65),
	('France', 65),
	('Germany', 65),
	('Italy', 65),
	('Japanese', 65),
	('Korean', 65),
	('New Zealand', 65),
	('Portugal', 65),
	('South Africa', 65),
	('Spain ', 65),
	('USA', 65),
	('Brandy', 66),
	('Whisky', 66),
	('Gin, Vodka & Rum', 66),
	('Tequila', 66),
	('Liquors', 66),
	('Cocktail Mixes', 66),
	('Wine System', 67),
	('Corkscrew & Bottle Opener', 67),
	('Drinking Glass', 67),
	('Superfoods', 68),
	('Bird''s Nest', 68),
	('Essence & Vitamins', 68),
	('Health Supplements', 68),
	('Tonics', 68),
	('Colouring & Styling', 69),
	('Conditioners', 69),
	('Shampoo', 69),
	('Treatment', 69),
	('Eye Care', 70),
	('Skin Care', 70),
	('Facial Cleansers', 70),
	('Facial Masks', 70),
	('Shavers', 70),
	('For Him', 70),
	('Dental Aid', 71),
	('Mouthwash', 71),
	('Toothbrush', 71),
	('Toothpaste', 71),
	('Bar Soap', 72),
	('Body Powder', 72),
	('Body Wash', 72),
	('Creams & Lotions', 72),
	('Deodorants', 72),
	('Derma Skincare', 72),
	('Hair Removal', 72),
	('Sunscreens', 72),
	('Hand Cream', 73),
	('Hand Sanitizer', 73),
	('Liquid Hand Soap', 73),
	('Nail Care', 73),
	('Foot Cream & Powder', 73),
	('Support & Accessories', 73),
	('Face', 74),
	('Eye Makeup', 74),
	('Lip Makeup', 74),
	('Makeup Removers', 74),
	('Female Hygiene', 75),
	('Pantiliners', 75),
	('Sanitary Pads', 75),
	('Tampons', 75),
	('Adult Care', 76),
	('Adult Diapers', 76),
	('Disposable Underwear', 76),
	('Condoms', 77),
	('Lubricants', 77),
	('Pregnancy Test Kits', 77),
	('Sexual Aids', 77),
	('Applied Medicine', 78),
	('Oral Medicine', 78),
	('Baby Health Care', 78),
	('Masks', 78),
	('Hair Dryers', 79),
	('Shavers & Trimmers', 79),
	('Hair Straighteners', 79),
	('Bleaches', 80),
	('Fabric Fresheners', 80),
	('Fabric Conditioners', 80),
	('Laundry Aids', 80),
	('Softeners', 80),
	('Stain Removers', 80),
	('Liquid Detergents', 81),
	('Powder Detergents', 81),
	('Anti-Bacterial', 82),
	('Regular', 82),
	('Pastes, Tablets & Others', 82),
	('Bathroom', 83),
	('Kitchen', 83),
	('Floor', 83),
	('Cleaning Tools', 83),
	('Disinfectants', 83),
	('Furniture & Glass', 83),
	('Shoe Care', 83),
	('Air Fresheners', 84),
	('Car Fresheners', 84),
	('Deodorizers', 84),
	('Dehumidifiers', 84),
	('Insecticides & Insect Killers', 85),
	('Insect Repellents', 85),
	('Baits, Traps & Devices', 85),
	('Bathroom Tissues', 86),
	('Facial Tissues', 86),
	('Kitchen Towels', 86),
	('Dry & Wet Wipes', 86),
	('Baking Paper, Foil, Wrap', 87),
	('Bakeware', 87),
	('Cookware', 87),
	('Food Containers', 87),
	('Garbage Bags & Bin Liners', 87),
	('Kitchen Tools', 87),
	('Storage Bags', 87),
	('Tableware ', 87),
	('Waterbottles & Jugs', 87),
	('Bathroom Accessories', 88),
	('Laundry Accessories', 88),
	('Towel & Tablecloth', 88),
	('Carriers & Trolleys', 88),
	('Furniture', 88),
	('Home & Travel Storage', 88),
	('Hooks & Organizers', 88),
	('Home Improvement & DIY', 88),
	('Writing Materials', 89),
	('Files', 89),
	('Office & School Essentials', 89),
	('Arts & Crafts', 89),
	('Tapes & Adhesives', 89),
	('Alkaline & Lithium Batteries', 89),
	('Rechargeable Batteries', 89),
	('Party Decorations', 90),
	('BBQ Accessories', 90),
	('Garbage Bags & Bin Liners', 90),
	('Food Trays & Utensils', 90),
	('Bowls & Plates', 90),
	('Cups & Glasses', 90),
	('Cutlery, Straws & Stirrers', 90),
	('Electronics & IT Gadgets', 91),
	('Extensions & Adaptors', 91),
	('Air Conditioners', 92),
	('Irons', 92),
	('Garment Steamers', 92),
	('Fans', 92),
	('Vacuum Cleaners', 92),
	('Microwaves', 92),
	('Ovens', 92),
	('Toasters', 92),
	('Rice Cookers', 92),
	('Multi Cookers', 92),
	('Electric Food Steamers', 92),
	('Blenders & Mixers', 92),
	('Air Fryers', 92),
	('Kettles & Air Pots', 92),
	('Induction Hobs', 92),
	('Coffee Machines', 92),
	('Other Cookware', 92),
	('Large Appliances', 92),
	('Books', 93),
	('Games & Toys', 93),
	('Soft Toys', 93),
	('Sports & Fitness ', 93),
	('Car Accessories', 94),
	('Car Fresheners', 94),
	('Bicycles', 94),
	('LED Bulbs & Lamps', 95),
	('Fluorescent Bulbs & Lamps', 95),
	('Halogen Bulbs & Lamps', 95),
	('Garden Accessories', 96),
	('For Aquatic Animals', 97),
	('For Reptiles', 97),
	('For Cats', 97),
	('For Dogs', 97),
	('For Small Pets', 97);