-- INSERT PRODUCTS

USE OnShop1939213;
GO

INSERT INTO 
	dbo.product(product_name, product_desc, measurements, is_available, is_in_stock, brand_id, category_id)
VALUES
('Attack Liquid Detergent - Perfume (Floral)', 'detergent, smells good, Liquid Detergent - Perfume (Floral) ', '3.6kg', 1, 1, 1, 472),
('Attack Liquid Detergent - Perfume (Floral)', 'detergent, smells good, Liquid Detergent - Perfume (Floral) ', '3 x 3.6kg (CTN)', 1, 1, 1, 472),
('Attack Liquid Detergent - Plus Colour (Aroma Fresh)', 'detergent, smells good, Liquid Detergent - Plus Colour (Aroma Fresh) ', '3.6kg', 1, 1, 1, 472),
('Attack Liquid Detergent - Plus Colour (Aroma Fresh)', 'detergent, smells good, Liquid Detergent - Plus Colour (Aroma Fresh) ', '3 x 3.6kg (CTN)', 1, 1, 1, 472),
('Attack Liquid Detergent - Plus Softener', 'detergent, smells good, Liquid Detergent - Plus Softener ', '3.6kg', 1, 1, 1, 472),
('Attack Liquid Detergent - Plus Softener', 'detergent, smells good, Liquid Detergent - Plus Softener ', '3 x 3.6kg (CTN)', 1, 1, 1, 472),
('Attack Liquid Detergent - Ultra Power (Aromatic Floral)', 'detergent, smells good, Liquid Detergent - Ultra Power (Aromatic Floral) ', '4kg', 1, 1, 1, 472),
('Attack Liquid Detergent - Ultra Power (Aromatic Floral)', 'detergent, smells good, Liquid Detergent - Ultra Power (Aromatic Floral) ', '3 x 4kg (CTN)', 1, 1, 1, 472),
('Attack Liquid Detergent Refill - Perfume (Floral)', 'detergent, smells good, Liquid Detergent Refill - Perfume (Floral) ', '1.4kg', 1, 1, 1, 472),
('Attack Liquid Detergent Refill - Plus Colour (Aroma Fresh)', 'detergent, smells good, Liquid Detergent Refill - Plus Colour (Aroma Fresh) ', '1.4kg', 1, 1, 1, 472),
('Attack Liquid Detergent Refill - Plus Softener', 'detergent, smells good, Liquid Detergent Refill - Plus Softener ', '1.4kg', 1, 1, 1, 472),
('Attack Liquid Detergent Refill - Ultra Power (Aromatic Floral)', 'detergent, smells good, Liquid Detergent Refill - Ultra Power (Aromatic Floral) ', '1.6kg', 1, 1, 1, 472),
('Bio-D Laundry Liquid Fragrance Free', 'detergent, smells good, Laundry Liquid Fragrance Free ', '1L', 1, 0, 2, 472),
('Bio-D Laundry Liquid With Juniper And Seaweed', 'detergent, smells good, Laundry Liquid With Juniper And Seaweed ', '1L', 1, 0, 2, 472),
('Bio-D Laundry Liquid With Lavender', 'detergent, smells good, Laundry Liquid With Lavender ', '5L', 1, 0, 2, 472),
('Bio-D Laundry Liquid With Lavender', 'detergent, smells good, Laundry Liquid With Lavender ', '1L', 1, 0, 2, 472),
('Bio-Home Laundry Detergent - Hyacinth & Nectarine', 'detergent, smells good, Laundry Detergent - Hyacinth & Nectarine ', '1.5L', 1, 0, 3, 472),
('Bio-Home Laundry Detergent Delicate - Hyacinth & Nectarine', 'detergent, smells good, Laundry Detergent Delicate - Hyacinth & Nectarine ', '1.5L', 1, 1, 3, 472),
('Breeze Liquid Detergent - Anti-Bacterial & Colour Protect', 'detergent, smells good, Liquid Detergent - Anti-Bacterial & Colour Protect ', '3.8kg', 1, 1, 4, 472),
('Breeze Liquid Detergent - Colour Care', 'detergent, smells good, Liquid Detergent - Colour Care ', '3.8kg', 1, 1, 4, 472),
('Breeze Liquid Detergent - Colour Care', 'detergent, smells good, Liquid Detergent - Colour Care ', '2.6kg', 1, 1, 4, 472),
('Breeze Liquid Detergent - Comfort (Long Lasting Perfume)', 'detergent, smells good, Liquid Detergent - Comfort (Long Lasting Perfume) ', '2.5kg', 1, 1, 4, 472),
('Breeze Liquid Detergent - Fragrance of Comfort', 'detergent, smells good, Liquid Detergent - Fragrance of Comfort ', '3.6kg', 1, 1, 4, 472),
('Breeze Liquid Detergent - Gentle on Skin', 'detergent, smells good, Liquid Detergent - Gentle on Skin ', '3.6kg', 1, 1, 4, 472),
('Breeze Liquid Detergent - Goodbye Musty (Indoor Drying)', 'detergent, smells good, Liquid Detergent - Goodbye Musty (Indoor Drying) ', '3.8kg', 1, 1, 4, 472),
('Breeze Liquid Detergent - Luxury Perfume', 'detergent, smells good, Liquid Detergent - Luxury Perfume ', '3.6kg', 1, 1, 4, 472),
('Breeze Liquid Detergent - Power Clean', 'detergent, smells good, Liquid Detergent - Power Clean ', '3.8kg', 1, 1, 4, 472),
('Breeze Liquid Detergent - Power Clean', 'detergent, smells good, Liquid Detergent - Power Clean ', '2.6kg', 1, 1, 4, 472),
('Breeze Liquid Detergent Refill - Anti-Bacterial & ColourProtect', 'detergent, smells good, Liquid Detergent Refill - Anti-Bacterial & ColourProtect ', '1.5kg', 1, 1, 4, 472),
('Breeze Liquid Detergent Refill - Colour Care', 'detergent, smells good, Liquid Detergent Refill - Colour Care ', '1.8kg', 1, 1, 4, 472),
('Breeze Liquid Detergent Refill - Gentle on Skin', 'detergent, smells good, Liquid Detergent Refill - Gentle on Skin ', '1.5kg', 1, 1, 4, 472),
('Breeze Liquid Detergent Refill - Power Clean ', 'detergent, smells good, Liquid Detergent Refill - Power Clean  ', '1.8kg', 1, 1, 4, 472),
('Dynamo Power Gel Laundry Detergent - Anti-Bacterial', 'detergent, smells good, Power Gel Laundry Detergent - Anti-Bacterial ', '2.7kg', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent - Anti-bacterial', 'detergent, smells good, Power Gel Laundry Detergent - Anti-bacterial ', '4 x 2.7kg (CTN)', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent - Color Care', 'detergent, smells good, Power Gel Laundry Detergent - Color Care ', '4 x 2.7kg (CTN)', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent - Color Care ', 'detergent, smells good, Power Gel Laundry Detergent - Color Care  ', '2.7L', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent - Downy', 'detergent, smells good, Power Gel Laundry Detergent - Downy ', '2.7L', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent - Downy', 'detergent, smells good, Power Gel Laundry Detergent - Downy ', '4 x 2.7kg (CTN)', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent - Indoor Dry', 'detergent, smells good, Power Gel Laundry Detergent - Indoor Dry ', '2.7kg', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent - Indoor Dry', 'detergent, smells good, Power Gel Laundry Detergent - Indoor Dry ', '4 x 2.7kg (CTN)', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent - Regular', 'detergent, smells good, Power Gel Laundry Detergent - Regular ', '3kg', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent - Regular', 'detergent, smells good, Power Gel Laundry Detergent - Regular ', '4 x 3kg (CTN)', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent Refill - Anti-bact', 'detergent, smells good, Power Gel Laundry Detergent Refill - Anti-bact ', '3 x 2.4kg (CTN)', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent Refill - Anti-bacterial ', 'detergent, smells good, Power Gel Laundry Detergent Refill - Anti-bacterial  ', '2.4kg', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent Refill - Anti-bacterial ', 'detergent, smells good, Power Gel Laundry Detergent Refill - Anti-bacterial  ', '1.44L', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent Refill - Color Care', 'detergent, smells good, Power Gel Laundry Detergent Refill - Color Care ', '1.44kg', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent Refill - Downy', 'detergent, smells good, Power Gel Laundry Detergent Refill - Downy ', '2.4kg', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent Refill - Downy', 'detergent, smells good, Power Gel Laundry Detergent Refill - Downy ', '3 x 2.4kg (CTN)', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent Refill - Downy', 'detergent, smells good, Power Gel Laundry Detergent Refill - Downy ', '1.44L', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent Refill - Indoor Dry', 'detergent, smells good, Power Gel Laundry Detergent Refill - Indoor Dry ', '2.4kg', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent Refill - IndoorDry', 'detergent, smells good, Power Gel Laundry Detergent Refill - IndoorDry ', '3 x 2.4kg (CTN)', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent Refill - Regular', 'detergent, smells good, Power Gel Laundry Detergent Refill - Regular ', '2.7kg', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent Refill - Regular', 'detergent, smells good, Power Gel Laundry Detergent Refill - Regular ', '3 x 2.7kg (CTN)', 1, 1, 5, 472),
('Dynamo Power Gel Laundry Detergent Refill - Regular ', 'detergent, smells good, Power Gel Laundry Detergent Refill - Regular  ', '1.6L', 1, 1, 5, 472),
('Earth Choice Laundry Liquid Detergent - Pure Clean', 'detergent, smells good, Choice Laundry Liquid Detergent - Pure Clean ', '1L', 1, 1, 6, 472),
('Earth Choice Wool & Delicates Liquid Detergent - Eucalyptus Fresh', 'detergent, smells good, Choice Wool & Delicates Liquid Detergent - Eucalyptus Fresh ', '1L', 1, 1, 6, 472),
('Ecomax 2X Conc. Hypoallergenic Laundry Wash', 'detergent, smells good, 2X Conc. Hypoallergenic Laundry Wash ', '1.5L', 1, 0, 7, 472),
('Ecomax 2X Conc. Natural Lavender Laundry Wash', 'detergent, smells good, 2X Conc. Natural Lavender Laundry Wash ', '1.5L', 1, 0, 7, 472),
('Ecomax 2X Conc. Natural Orange Laundry Wash', 'detergent, smells good, 2X Conc. Natural Orange Laundry Wash ', '1.5L', 1, 0, 7, 472),
('Ecomax Hypoallergenic Laundry Wash', 'detergent, smells good, Hypoallergenic Laundry Wash ', '3L', 1, 0, 7, 472),
('Ecomax Natural Orange Laundry Wash', 'detergent, smells good, Natural Orange Laundry Wash ', '3L', 1, 0, 7, 472),
('Ecostore Wool & Delicates Eucalyptus', 'detergent, smells good, Wool & Delicates Eucalyptus ', '1L', 1, 0, 8, 472),
('Ecover Laundry Liquid - Delicate', 'detergent, smells good, Laundry Liquid - Delicate ', '750ml', 1, 1, 9, 472),
('Ecover Zero Concentrated Laundry Liquid - Non-Bio', 'detergent, smells good, Zero Concentrated Laundry Liquid - Non-Bio ', '1.5L', 1, 1, 9, 472),
('Ecover ZERO Wool & Delicates Laundry Liquid', 'detergent, smells good, ZERO Wool & Delicates Laundry Liquid ', '1 L', 1, 0, 9, 472),
('Essence Delicate Laundry Detergent - Anti-Bacterial', 'detergent, smells good, Delicate Laundry Detergent - Anti-Bacterial ', '1L', 1, 1, 10, 472),
('Essence Delicate Laundry Detergent - Floral', 'detergent, smells good, Delicate Laundry Detergent - Floral ', '1L', 1, 1, 10, 472),
('Essence Delicate Laundry Detergent - Machine Wash', 'detergent, smells good, Delicate Laundry Detergent - Machine Wash ', '1L', 1, 1, 10, 472),
('Essence Delicate Laundry Detergent Refill - Anti-Bacteria', 'detergent, smells good, Delicate Laundry Detergent Refill - Anti-Bacteria ', '800ml', 1, 1, 10, 472),
('Essence Delicate Laundry Detergent Refill - Floral', 'detergent, smells good, Delicate Laundry Detergent Refill - Floral ', '800ml', 1, 1, 10, 472),
('Essence Delicate Laundry Detergent Refill - Machine Wash', 'detergent, smells good, Delicate Laundry Detergent Refill - Machine Wash ', '800ml', 1, 1, 10, 472),
('FairPrice Laundry Liquid Detergent - Anti-Bacterial', 'detergent, smells good, Laundry Liquid Detergent - Anti-Bacterial ', '4.4L', 1, 1, 12, 472),
('FairPrice Laundry Liquid Detergent - Colour Care', 'detergent, smells good, Laundry Liquid Detergent - Colour Care ', '4.4L', 1, 1, 12, 472),
('FairPrice Laundry Liquid Detergent - Flora', 'detergent, smells good, Laundry Liquid Detergent - Flora ', '4.4L', 1, 1, 12, 472),
('FairPrice Laundry Liquid Detergent Refill - Anti-Bacterial', 'detergent, smells good, Laundry Liquid Detergent Refill - Anti-Bacterial ', '1.8L', 1, 1, 12, 472),
('FairPrice Laundry Liquid Detergent Refill - Colour Care', 'detergent, smells good, Laundry Liquid Detergent Refill - Colour Care ', '1.8L', 1, 1, 12, 472),
('FairPrice Laundry Liquid Detergent Refill - Flora', 'detergent, smells good, Laundry Liquid Detergent Refill - Flora ', '1.8L', 1, 1, 12, 472),
('Green Kulture Laundry Liquid', 'detergent, smells good, Kulture Laundry Liquid ', '1L', 1, 1, 14, 472),
('Green Kulture Laundry Liquid - Delicate', 'detergent, smells good, Kulture Laundry Liquid - Delicate ', '1L', 1, 1, 14, 472),
('Greenscent Organic Laundry Liquid - Lavender', 'detergent, smells good, Organic Laundry Liquid - Lavender ', '500ml', 1, 0, 15, 472),
('Greenscent Organic Laundry Liquid - Non Scent', 'detergent, smells good, Organic Laundry Liquid - Non Scent ', '500ml', 1, 0, 15, 472),
('Kirkland Signature Premium Laundry Detergent Pacs - Ultra Clean', 'detergent, smells good, Signature Premium Laundry Detergent Pacs - Ultra Clean ', '3.6kg', 1, 1, 16, 472),
('Kirkland Signature Ultra Clean Laundry Detergent - Refreshing', 'detergent, smells good, Signature Ultra Clean Laundry Detergent - Refreshing ', '5.73L', 1, 1, 16, 472),
('Method 4x Concentrated Laundry Detergent - Ginger & Mango ', 'detergent, smells good, 4x Concentrated Laundry Detergent - Ginger & Mango  ', '1.58L', 1, 1, 20, 472),
('Method Laundry Detergent - Fresh Air (50 Loads)', 'detergent, smells good, Laundry Detergent - Fresh Air (50 Loads) ', '600 ML', 1, 0, 20, 472),
('Method Laundry Detergent - Lavender Cypress', 'detergent, smells good, Laundry Detergent - Lavender Cypress ', '1.58 L', 1, 0, 20, 472),
('Method Laundry Detergent - Spring Garden (66 Loads)', 'detergent, smells good, Laundry Detergent - Spring Garden (66 Loads) ', '1.58 L', 1, 0, 20, 472),
('Method Laundry Detergent Packs - Beach Sage', 'detergent, smells good, Laundry Detergent Packs - Beach Sage ', '42 Pc', 1, 0, 20, 472),
('Method Laundry Detergent Packs - Ginger Mango', 'detergent, smells good, Laundry Detergent Packs - Ginger Mango ', '42 pc', 1, 0, 20, 472),
('Method Laundry Detergent Refill - Fresh Air (85 Loads)', 'detergent, smells good, Laundry Detergent Refill - Fresh Air (85 Loads) ', '1 L', 1, 0, 20, 472),
('Persil Concentrated Liquid Detergent - Anti-Bacterial', 'detergent, smells good, Concentrated Liquid Detergent - Anti-Bacterial ', '2.7L', 1, 1, 21, 472),
('Persil Concentrated Liquid Detergent - Front Load', 'detergent, smells good, Concentrated Liquid Detergent - Front Load ', '3L', 1, 1, 21, 472),
('Persil Concentrated Liquid Detergent - Sensitive', 'detergent, smells good, Concentrated Liquid Detergent - Sensitive ', '2.7L', 1, 1, 21, 472),
('Perwoll Liquid Detergent For Wool & Delicates', 'detergent, smells good, Liquid Detergent For Wool & Delicates ', '1.5L', 1, 1, 22, 472),
('Perwoll with ReNew+ Black Effect Laundry Liquid Detergent', 'detergent, smells good, with ReNew+ Black Effect Laundry Liquid Detergent ', '1.5L', 1, 1, 22, 472),
('PiPPER Laundry Detergent Eucalyptus', 'detergent, smells good, Laundry Detergent Eucalyptus ', '4.5L', 1, 0, 23, 472),
('PiPPER Laundry Detergent Lemongrass', 'detergent, smells good, Laundry Detergent Lemongrass ', '4.5L', 1, 0, 23, 472),
('PiPPER Standard Laundry Detergent Eucalyptus', 'detergent, smells good, Standard Laundry Detergent Eucalyptus ', '900ml', 1, 0, 23, 472),
('PiPPER Standard Laundry Detergent Eucalyptus', 'detergent, smells good, Standard Laundry Detergent Eucalyptus ', '6 x 900ml (CTN)', 1, 0, 23, 472),
('PiPPER Standard Laundry Detergent Eucalyptus Refill', 'detergent, smells good, Standard Laundry Detergent Eucalyptus Refill ', '750ml', 1, 0, 23, 472),
('PiPPER Standard Laundry Detergent Eucalyptus Refill', 'detergent, smells good, Standard Laundry Detergent Eucalyptus Refill ', '12 x 750ml (CTN)', 1, 0, 23, 472),
('PiPPER Standard Laundry Detergent Lemongrass', 'detergent, smells good, Standard Laundry Detergent Lemongrass ', '900ml', 1, 0, 23, 472),
('PiPPER Standard Laundry Detergent Lemongrass', 'detergent, smells good, Standard Laundry Detergent Lemongrass ', '6 x 900ml (CTN)', 1, 0, 23, 472),
('PiPPER Standard Laundry Detergent Lemongrass Refill', 'detergent, smells good, Standard Laundry Detergent Lemongrass Refill ', '750ml', 1, 0, 23, 472),
('PiPPER Standard Laundry Detergent Lemongrass Refill', 'detergent, smells good, Standard Laundry Detergent Lemongrass Refill ', '12 x 750ml (CTN)', 1, 0, 23, 472),
('PiPPER Standard Travel Set - Ldry Detergent + Stn Remover', 'detergent, smells good, Standard Travel Set - Ldry Detergent + Stn Remover ', '90ml + 30ml', 1, 0, 23, 472),
('Seventh Generation Natural Laundry Detergent - Free & Clear', 'detergent, smells good, Generation Natural Laundry Detergent - Free & Clear ', '1.47L', 1, 1, 26, 472),
('Seventh Generation Natural Laundry Detergent - Fresh Citrus', 'detergent, smells good, Generation Natural Laundry Detergent - Fresh Citrus ', '1.47L', 1, 1, 26, 472),
('Seventh Generation Natural Laundry Detergent - Lavender', 'detergent, smells good, Generation Natural Laundry Detergent - Lavender ', '1.47L', 1, 1, 26, 472),
('SPINmatic Low Suds Liquid Detergent - Active Bright', 'detergent, smells good, Low Suds Liquid Detergent - Active Bright ', '3L', 1, 1, 27, 472),
('SPINmatic Low Suds Liquid Detergent - Anti-Bacterial', 'detergent, smells good, Low Suds Liquid Detergent - Anti-Bacterial ', '3L', 1, 1, 27, 472),
('SPINmatic Low Suds Liquid Detergent - Sports Freshness', 'detergent, smells good, Low Suds Liquid Detergent - Sports Freshness ', '2.7L', 1, 1, 27, 472),
('SPINmatic Low Suds Liquid Detergent Refill - Active Bright', 'detergent, smells good, Low Suds Liquid Detergent Refill - Active Bright ', '1.6L', 1, 1, 27, 472),
('SPINmatic Low Suds Liquid Detergent Refill - Anti-Bacterial', 'detergent, smells good, Low Suds Liquid Detergent Refill - Anti-Bacterial ', '1.6L', 1, 1, 27, 472),
('SPINmatic Low Suds Liquid Detergent Refill - Sports Freshness', 'detergent, smells good, Low Suds Liquid Detergent Refill - Sports Freshness ', '1.4L', 1, 1, 27, 472),
('Tide He Turbo Laundry Liquid Detergent - Original', 'detergent, smells good, He Turbo Laundry Liquid Detergent - Original ', '4.43L', 1, 1, 30, 472),
('Tide He Turbo Laundry Liquid Detergent - Original Scent', 'detergent, smells good, He Turbo Laundry Liquid Detergent - Original Scent ', '1.47L', 1, 1, 30, 472),
('Tide Laundry Liquid - Free & Gentle', 'detergent, smells good, Laundry Liquid - Free & Gentle ', '4.43L', 1, 1, 30, 472),
('Tide Laundry Liquid - Free & Gentle', 'detergent, smells good, Laundry Liquid - Free & Gentle ', '1.47L', 1, 1, 30, 472),
('Tide Laundry Liquid - Original', 'detergent, smells good, Laundry Liquid - Original ', '306ml', 1, 1, 30, 472),
('Tide Plus Laundry Liquid Detergent - Downy (April Fresh)', 'detergent, smells good, Plus Laundry Liquid Detergent - Downy (April Fresh) ', '1.36L', 1, 1, 30, 472),
('Tide Purclean Laundry Liquid Detergent - Honey Lavender', 'detergent, smells good, Purclean Laundry Liquid Detergent - Honey Lavender ', '1.47L', 1, 1, 30, 472),
('Tide Purclean Laundry Liquid Detergent - Honey Lavender', 'detergent, smells good, Purclean Laundry Liquid Detergent - Honey Lavender ', '2.21L', 1, 1, 30, 472),
('Tide Purclean Laundry Liquid Detergent - Unscented', 'detergent, smells good, Purclean Laundry Liquid Detergent - Unscented ', '2.22L', 1, 1, 30, 472),
('Tide Purclean Laundry Liquid Detergent - Unscented', 'detergent, smells good, Purclean Laundry Liquid Detergent - Unscented ', '1.47L', 1, 1, 30, 472),
('Top Concentrated Liquid Detergent - Blooming Freshness', 'detergent, smells good, Concentrated Liquid Detergent - Blooming Freshness ', '3.6kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent - Super Colour', 'detergent, smells good, Concentrated Liquid Detergent - Super Colour ', '4 x 2.8kg (CTN)', 1, 0, 31, 472),
('Top Concentrated Liquid Detergent - Super Low Suds', 'detergent, smells good, Concentrated Liquid Detergent - Super Low Suds ', '4 x 2.8kg (CTN)', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Bottle - Anti-Bac', 'detergent, smells good, Concentrated Liquid Detergent Bottle - Anti-Bac ', '4 x 2.6kg (CTN)', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Bottle - Anti-Bac', 'detergent, smells good, Concentrated Liquid Detergent Bottle - Anti-Bac ', '4 x 280ml (CTN)', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Bottle - Anti-Bacterial', 'detergent, smells good, Concentrated Liquid Detergent Bottle - Anti-Bacterial ', '4kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Bottle - Anti-Bacterial', 'detergent, smells good, Concentrated Liquid Detergent Bottle - Anti-Bacterial ', '2.8kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Bottle - Anti-Bacterial', 'detergent, smells good, Concentrated Liquid Detergent Bottle - Anti-Bacterial ', '2.6kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Bottle - Super Colour', 'detergent, smells good, Concentrated Liquid Detergent Bottle - Super Colour ', '4kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Bottle - Super Colour', 'detergent, smells good, Concentrated Liquid Detergent Bottle - Super Colour ', '2.6kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Bottle - Super Low Suds', 'detergent, smells good, Concentrated Liquid Detergent Bottle - Super Low Suds ', '2.8kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Bottle - Super White', 'detergent, smells good, Concentrated Liquid Detergent Bottle - Super White ', '4kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Bottle - Super White', 'detergent, smells good, Concentrated Liquid Detergent Bottle - Super White ', '2.6kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Bottle - SuperWhite', 'detergent, smells good, Concentrated Liquid Detergent Bottle - SuperWhite ', '4 x 2.6kg (CTN)', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Bottle-Super Colour', 'detergent, smells good, Concentrated Liquid Detergent Bottle-Super Colour ', '4 x 2.6kg (CTN)', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Refill - Anti-Bacterial', 'detergent, smells good, Concentrated Liquid Detergent Refill - Anti-Bacterial ', '1.6kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Refill - Anti-Bacterial', 'detergent, smells good, Concentrated Liquid Detergent Refill - Anti-Bacterial ', '1.5kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Refill - Blooming Fresh', 'detergent, smells good, Concentrated Liquid Detergent Refill - Blooming Fresh ', '300g', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Refill - Blooming Freshness', 'detergent, smells good, Concentrated Liquid Detergent Refill - Blooming Freshness ', '1.5kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Refill - Super Colour', 'detergent, smells good, Concentrated Liquid Detergent Refill - Super Colour ', '1.6kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Refill - Super Low Suds', 'detergent, smells good, Concentrated Liquid Detergent Refill - Super Low Suds ', '1.5kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent Refill - Super White', 'detergent, smells good, Concentrated Liquid Detergent Refill - Super White ', '1.6kg', 1, 1, 31, 472),
('Top Concentrated Liquid Detergent with Softener - Fresh Camomile', 'detergent, smells good, Concentrated Liquid Detergent with Softener - Fresh Camomile ', '900g', 1, 1, 31, 472),
('Top Nanox Ultra Concentrated Liquid Detergent - Anti-Bacterial', 'detergent, smells good, Nanox Ultra Concentrated Liquid Detergent - Anti-Bacterial ', '450g', 1, 1, 31, 472),
('Top Nanox Ultra Concentrated Liquid Detergent - Deo Bright', 'detergent, smells good, Nanox Ultra Concentrated Liquid Detergent - Deo Bright ', '450g', 1, 1, 31, 472),
('Top Nanox Ultra Concentrated Liquid Detergent Refill - Anti-Bact', 'detergent, smells good, Nanox Ultra Concentrated Liquid Detergent Refill - Anti-Bact ', '360g', 1, 1, 31, 472),
('Top Nanox Ultra Concentrated Liquid Detergent Refill - DeoBright', 'detergent, smells good, Nanox Ultra Concentrated Liquid Detergent Refill - DeoBright ', '360g', 1, 1, 31, 472),
('Top Pre-Care Collar Sleeves Liquid Detergent', 'detergent, smells good, Pre-Care Collar Sleeves Liquid Detergent ', '250ml', 1, 1, 31, 472),
('UIC Big Value Liquid Detergent - Anti-Bacterial', 'detergent, smells good, Big Value Liquid Detergent - Anti-Bacterial ', '4kg', 1, 1, 32, 472),
('UIC Big Value Liquid Detergent - Colour Care', 'detergent, smells good, Big Value Liquid Detergent - Colour Care ', '4kg', 1, 1, 32, 472),
('UIC Big Value Liquid Detergent - Floral', 'detergent, smells good, Big Value Liquid Detergent - Floral ', '4kg', 1, 1, 32, 472),
('UIC Big Value Liquid Detergent Refill - Anti-Bacterial', 'detergent, smells good, Big Value Liquid Detergent Refill - Anti-Bacterial ', '1.6kg', 1, 1, 32, 472),
('UIC Big Value Liquid Detergent Refill - Colour Care', 'detergent, smells good, Big Value Liquid Detergent Refill - Colour Care ', '1.6L', 1, 1, 32, 472),
('UIC Big Value Liquid Detergent Refill - Floral', 'detergent, smells good, Big Value Liquid Detergent Refill - Floral ', '1.8L + 600ml', 1, 1, 32, 472),
('UIC Big Value Liquid Detergent Refill - Floral ', 'detergent, smells good, Big Value Liquid Detergent Refill - Floral  ', '1.6kg', 1, 1, 32, 472),
('UIC Natural Plus Ultra Concentrated Laundry Liquid - Fresh Scent', 'detergent, smells good, Natural Plus Ultra Concentrated Laundry Liquid - Fresh Scent ', '1.5L', 1, 1, 32, 472),
('UIC Natural Plus Ultra Concentrated Laundry Liquid-Antibacterial', 'detergent, smells good, Natural Plus Ultra Concentrated Laundry Liquid-Antibacterial ', '1.5L', 1, 1, 32, 472),
('Walch Concentrated Detergent - Fresh Lemon', 'detergent, smells good, Concentrated Detergent - Fresh Lemon ', '3L', 1, 1, 33, 472),
('Walch Concentrated Detergent - Original', 'detergent, smells good, Concentrated Detergent - Original ', '3L', 1, 1, 33, 472),
('Walch Concentrated Detergent - Pine', 'detergent, smells good, Concentrated Detergent - Pine ', '3L', 1, 1, 33, 472),
('Woolite Hand Wash Liquid Detergent', 'detergent, smells good, Hand Wash Liquid Detergent ', '1L', 1, 1, 33, 472),
('Yuri Matic Laundry Liquid Low Suds - Lavender + Refill', 'detergent, smells good, Matic Laundry Liquid Low Suds - Lavender + Refill ', '2.8kg + 630g', 1, 1, 33, 472),
('Yuri-matic Laundry Liquid Detergent - Lavender (Low Suds)', 'detergent, smells good, Laundry Liquid Detergent - Lavender (Low Suds) ', '2.8kg', 1, 1, 33, 472),
('Yuri-matic Laundry Liquid Detergent - Romantic Blue', 'detergent, smells good, Laundry Liquid Detergent - Romantic Blue ', '2.8kg', 1, 1, 33, 472),
('Yuri-matic Laundry Liquid Detergent Refill - Floral', 'detergent, smells good, Laundry Liquid Detergent Refill - Floral ', '1.8kg', 1, 1, 33, 472),
('Yuri-matic Laundry Liquid Detergent Refill - Lavender (Low Suds)', 'detergent, smells good, Laundry Liquid Detergent Refill - Lavender (Low Suds) ', '1.8kg', 1, 1, 33, 472),
('Yuri-matic Laundry Liquid Detergent Refill - Romantic Blue', 'detergent, smells good, Laundry Liquid Detergent Refill - Romantic Blue ', '1.8kg', 1, 1, 35, 472),
('Yuri-matic Laundry Liquid Detergent with Refill - Floral', 'detergent, smells good, Laundry Liquid Detergent with Refill - Floral ', '2.8kg + 630g', 1, 1, 35, 472),
('Yuri-Matic Laundry Liquid Detergent with Refill - Romantic Blue', 'detergent, smells good, Laundry Liquid Detergent with Refill - Romantic Blue ', '2.8kg', 1, 1, 35, 472),
('Attack Powder Detergent - Plus Colour (Aroma Fresh)', 'detergent, smells good, Powder Detergent - Plus Colour (Aroma Fresh) ', '3kg', 1, 1, 1, 473),
('Attack Powder Detergent - Plus Softener (Sweet Floral)', 'detergent, smells good, Powder Detergent - Plus Softener (Sweet Floral) ', '2.8kg', 1, 1, 1, 473),
('Attack Powder Detergent - Ultra Power (Aromatic Floral)', 'detergent, smells good, Powder Detergent - Ultra Power (Aromatic Floral) ', '1.6kg', 1, 1, 1, 473),
('Attack Powder Detergent - Ultra Power (Aromatic Floral)', 'detergent, smells good, Powder Detergent - Ultra Power (Aromatic Floral) ', '3kg', 1, 1, 1, 473),
('Bio-D Washing Powder', 'detergent, smells good, Washing Powder ', '1kg', 1, 0, 2, 473),
('Breeze Powder Detergent - Colour Care ', 'detergent, smells good, Powder Detergent - Colour Care  ', '3.6kg', 1, 1, 4, 473),
('Breeze Powder Detergent - Colour Care ', 'detergent, smells good, Powder Detergent - Colour Care  ', '2.3kg', 1, 1, 4, 473),
('Breeze Powder Detergent - Colour Care ', 'detergent, smells good, Powder Detergent - Colour Care  ', '400g', 1, 1, 4, 473),
('Breeze Powder Detergent - Comfort (Long Lasting Perfume)', 'detergent, smells good, Powder Detergent - Comfort (Long Lasting Perfume) ', '3.3kg', 1, 1, 4, 473),
('Breeze Powder Detergent - Comfort (Long Lasting Perfume)', 'detergent, smells good, Powder Detergent - Comfort (Long Lasting Perfume) ', '2.1kg', 1, 1, 4, 473),
('Breeze Powder Detergent - Goodbye Musty', 'detergent, smells good, Powder Detergent - Goodbye Musty ', '2.3kg', 1, 1, 4, 473),
('Breeze Powder Detergent - Power Clean ', 'detergent, smells good, Powder Detergent - Power Clean  ', '400g', 1, 1, 4, 473),
('Breeze Powder Detergent - Power Clean ', 'detergent, smells good, Powder Detergent - Power Clean  ', '3.6kg', 1, 1, 4, 473),
('Breeze Powder Detergent - Power Clean ', 'detergent, smells good, Powder Detergent - Power Clean  ', '2.3kg', 1, 1, 4, 473),
('Dynamo Laundry Powder Detergent - Colour Care', 'detergent, smells good, Laundry Powder Detergent - Colour Care ', '2.1kg', 1, 1, 5, 473),
('Dynamo Laundry Powder Detergent - Downy', 'detergent, smells good, Laundry Powder Detergent - Downy ', '2.1kg', 1, 1, 5, 473),
('Dynamo Laundry Powder Detergent - Perfect Clean', 'detergent, smells good, Laundry Powder Detergent - Perfect Clean ', '2.3kg', 1, 1, 5, 473),
('Fab Detergent Powder - Anti-Bacterial', 'detergent, smells good, Detergent Powder - Anti-Bacterial ', '4.7kg', 1, 1, 11, 473),
('Fab Detergent Powder - Anti-Bacterial', 'detergent, smells good, Detergent Powder - Anti-Bacterial ', '2.1kg', 1, 1, 11, 473),
('Fab Detergent Powder - Downy', 'detergent, smells good, Detergent Powder - Downy ', '4.7kg', 1, 1, 11, 473),
('Fab Detergent Powder - Lavender ', 'detergent, smells good, Detergent Powder - Lavender  ', '4.7kg', 1, 1, 11, 473),
('Fab Detergent Powder - Perfect', 'detergent, smells good, Detergent Powder - Perfect ', '5.1kg', 1, 1, 11, 473),
('Fab Detergent Powder - Perfect', 'detergent, smells good, Detergent Powder - Perfect ', '2.3kg', 1, 1, 11, 473),
('Fab Detergent Powder - Perfect', 'detergent, smells good, Detergent Powder - Perfect ', '720g', 1, 1, 11, 473),
('Fab Detergent Powder - Professional', 'detergent, smells good, Detergent Powder - Professional ', '8.5kg', 1, 1, 11, 473),
('FairPrice Machine Wash Detergent Powder - Front Load', 'detergent, smells good, Machine Wash Detergent Powder - Front Load ', '3.5kg', 1, 1, 12, 473),
('FairPrice Machine Wash Detergent Powder - Top Load', 'detergent, smells good, Machine Wash Detergent Powder - Top Load ', '3.5kg', 1, 1, 12, 473),
('FairPrice Triple Action Detergent Powder', 'detergent, smells good, Triple Action Detergent Powder ', '5kg + free 750g', 1, 1, 12, 473),
('FairPrice Triple Action Detergent Powder', 'detergent, smells good, Triple Action Detergent Powder ', '1kg + free 200g', 1, 1, 12, 473),
('FairPrice Triple Action Detergent Powder ', 'detergent, smells good, Triple Action Detergent Powder  ', '3.5kg', 1, 1, 12, 473),
('Labour Laundry Soap Bar', 'detergent, smells good, Laundry Soap Bar ', '5 x 100g', 1, 1, 17, 473),
('Look Detergent Powder - Multi Action', 'detergent, smells good, Detergent Powder - Multi Action ', '5kg', 1, 1, 18, 473),
('Look Detergent Powder - Multi Action', 'detergent, smells good, Detergent Powder - Multi Action ', '1kg', 1, 1, 18, 473),
('Look Detergent Powder - Multi Action (Anti-Bacterial)', 'detergent, smells good, Detergent Powder - Multi Action (Anti-Bacterial) ', '1kg', 1, 1, 18, 473),
('Mama Laundry Detergent Powder', 'detergent, smells good, Laundry Detergent Powder ', '1kg', 1, 1, 19, 473),
('Persil Powder Detergent - Anti-Bacterial', 'detergent, smells good, Powder Detergent - Anti-Bacterial ', '4.5kg', 1, 1, 21, 473),
('Persil Powder Detergent - Fibre Intelligent', 'detergent, smells good, Powder Detergent - Fibre Intelligent ', '3kg', 1, 1, 21, 473),
('Persil Powder Detergent - Front Load', 'detergent, smells good, Powder Detergent - Front Load ', '5kg', 1, 1, 21, 473),
('Promax Super Detergent Powder - Floral Fresh', 'detergent, smells good, Super Detergent Powder - Floral Fresh ', '5.75kg', 1, 1, 24, 473),
('Promax Super Detergent Powder - Lemon Fresh', 'detergent, smells good, Super Detergent Powder - Lemon Fresh ', '5.75kg', 1, 1, 24, 473),
('Promax Super Detergent Powder - Lemon Fresh', 'detergent, smells good, Super Detergent Powder - Lemon Fresh ', '1kg', 1, 1, 24, 473),
('Rin - Bright Like New', 'detergent, smells good, - Bright Like New ', '1kg', 1, 0, 25, 473),
('SPINmatic Low Suds Detergent Powder - Active Bright', 'detergent, smells good, Low Suds Detergent Powder - Active Bright ', '5kg', 1, 1, 27, 473),
('SPINmatic Low Suds Detergent Powder - Active Bright ', 'detergent, smells good, Low Suds Detergent Powder - Active Bright  ', '5kg + free 500g', 1, 1, 27, 473),
('SPINmatic Low Suds Detergent Powder - Anti-Bacterial', 'detergent, smells good, Low Suds Detergent Powder - Anti-Bacterial ', '5.5kg', 1, 1, 27, 473),
('SPINmatic Low Suds Detergent Powder - Anti-Bacterial ', 'detergent, smells good, Low Suds Detergent Powder - Anti-Bacterial  ', '3kg', 1, 1, 27, 473),
('Tesco Oxy Power Powder Detergent - Colours', 'detergent, smells good, Oxy Power Powder Detergent - Colours ', '1kg', 1, 1, 29, 473),
('Top Detergent Powder - Anti-Bacterial', 'detergent, smells good, Detergent Powder - Anti-Bacterial ', '5.5kg', 1, 1, 31, 473),
('Top Detergent Powder - Anti-Bacterial', 'detergent, smells good, Detergent Powder - Anti-Bacterial ', '2.5kg', 1, 1, 31, 473),
('Top Detergent Powder - Anti-Bacterial', 'detergent, smells good, Detergent Powder - Anti-Bacterial ', '4kg', 1, 1, 31, 473),
('Top Detergent Powder - Blooming Freshness', 'detergent, smells good, Detergent Powder - Blooming Freshness ', '5kg', 1, 1, 31, 473),
('Top Detergent Powder - Blooming Freshness', 'detergent, smells good, Detergent Powder - Blooming Freshness ', '2.3kg', 1, 1, 31, 473),
('Top Detergent Powder - Blooming Freshness', 'detergent, smells good, Detergent Powder - Blooming Freshness ', '3.6kg', 1, 1, 31, 473),
('Top Detergent Powder - Super Colour', 'detergent, smells good, Detergent Powder - Super Colour ', '5.5kg', 1, 1, 31, 473),
('Top Detergent Powder - Super Colour', 'detergent, smells good, Detergent Powder - Super Colour ', '2.5kg', 1, 1, 31, 473),
('Top Detergent Powder - Super Colour', 'detergent, smells good, Detergent Powder - Super Colour ', '4kg', 1, 1, 31, 473),
('Top Detergent Powder - Super White', 'detergent, smells good, Detergent Powder - Super White ', '5.5kg', 1, 1, 31, 473),
('Top Detergent Powder - Super White', 'detergent, smells good, Detergent Powder - Super White ', '2.5kg', 1, 1, 31, 473),
('Top Detergent Powder Packet Super Low Suds - Anti-Bacterial', 'detergent, smells good, Detergent Powder Packet Super Low Suds - Anti-Bacterial ', '3kg', 1, 1, 31, 473),
('Top Detergent Powder Packet Super Low Suds - Colour Protect ', 'detergent, smells good, Detergent Powder Packet Super Low Suds - Colour Protect  ', '3kg', 1, 1, 31, 473),
('UIC Active Power Laundry Powder Detergent - Musty Removal', 'detergent, smells good, Active Power Laundry Powder Detergent - Musty Removal ', '500g', 1, 1, 32, 473),
('UIC Active Power Laundry Powder Detergent - Musty Removal', 'detergent, smells good, Active Power Laundry Powder Detergent - Musty Removal ', '5.5kg', 1, 1, 32, 473),
('UIC Active Power Laundry Powder Detergent - Regular', 'detergent, smells good, Active Power Laundry Powder Detergent - Regular ', '500g', 1, 1, 32, 473),
('UIC Active Power Laundry Powder Detergent - Regular', 'detergent, smells good, Active Power Laundry Powder Detergent - Regular ', '5.5kg', 1, 1, 32, 473),
('UIC Active Power+ Powder Detergent - Musty Removal', 'detergent, smells good, Active Power+ Powder Detergent - Musty Removal ', '2.5kg', 1, 1, 32, 473),
('UIC Active Power+ Powder Detergent - Regular', 'detergent, smells good, Active Power+ Powder Detergent - Regular ', '2.5kg', 1, 1, 32, 473),
('UIC Big Value Detergent Powder - Anti Bacterial (Citrus Splash)', 'detergent, smells good, Big Value Detergent Powder - Anti Bacterial (Citrus Splash) ', '1kg', 1, 1, 32, 473),
('UIC Big Value Detergent Powder - Anti Bacterial (Citrus Splash)', 'detergent, smells good, Big Value Detergent Powder - Anti Bacterial (Citrus Splash) ', '5kg', 1, 1, 32, 473),
('UIC Big Value Detergent Powder - Anti Bacterial (Citrus Splash)', 'detergent, smells good, Big Value Detergent Powder - Anti Bacterial (Citrus Splash) ', '3kg', 1, 1, 32, 473),
('UIC Big Value Detergent Powder - Regular (Floral Fruity)', 'detergent, smells good, Big Value Detergent Powder - Regular (Floral Fruity) ', '3kg', 1, 1, 32, 473),
('UIC Big Value Detergent Powder - Regular (Floral Fruity)', 'detergent, smells good, Big Value Detergent Powder - Regular (Floral Fruity) ', '1kg', 1, 1, 32, 473),
('UIC Big Value Detergent Powder - Regular (Floral Fruity)', 'detergent, smells good, Big Value Detergent Powder - Regular (Floral Fruity) ', '1kg + 200g', 1, 0, 32, 473),
('UIC Big Value Detergent Powder - AntiBacterial(Citrus)', 'detergent, smells good, Big Value Detergent Powder - AntiBacterial(Citrus) ', '5kg + free 500g', 1, 1, 32, 473),
('UIC Big Value Detergent Powder - Regular(FloralFruity)', 'detergent, smells good, Big Value Detergent Powder - Regular(FloralFruity) ', '5kg + free 500g', 1, 1, 32, 473),
('Ujala - Detergent Washing Powder', 'detergent, smells good, - Detergent Washing Powder ', '1kg', 1, 1, 33, 473),
('MAND Portable Cable Reels (6m)', 'Portable Cable Reels (6m) ', '1S', 1, 1, 39, 537),
('Morries Extension Cord - 3 Way with USB (MS3333-USB)', 'Extension Cord - 3 Way with USB (MS3333-USB) ', '1 per pack', 1, 1, 40, 537),
('Morries Extension Cord - 4 Way with USB (MS3344-USB)', 'Extension Cord - 4 Way with USB (MS3344-USB) ', '1 per pack', 1, 1, 40, 537),
('Morries Extension Cord - 5 Way with USB (MS3355-USB)', 'Extension Cord - 5 Way with USB (MS3355-USB) ', '1 per pack', 1, 1, 40, 537),
('Morries Travel Adaptor (MS-002)', 'Travel Adaptor (MS-002) ', '1 per pack', 1, 1, 40, 537),
('Morries USB Travel Adaptor (MS-006BK)', 'USB Travel Adaptor (MS-006BK) ', '1 per pack', 1, 1, 40, 537),
('Morries USB Travel Adaptor (MS-S25)', 'USB Travel Adaptor (MS-S25) ', '1 per pack', 1, 1, 40, 537),
('PowerPac 2 Way 3M Extension Cord With 2-Pin Direct PP3882N', '2 Way 3M Extension Cord With 2-Pin Direct PP3882N ', '1 Pc', 1, 0, 41, 537),
('PowerPac 24hrs Timer Plug FDD50-AS1', '24hrs Timer Plug FDD50-AS1 ', '1 Pc', 1, 0, 41, 537),
('PowerPac 24hrs Timer Plug FDD50-E1', '24hrs Timer Plug FDD50-E1 ', '1 pc', 1, 0, 41, 537),
('PowerPac 2Pin 3Way Extension Cord 3M With Safety Shutter PP260N', '2Pin 3Way Extension Cord 3M With Safety Shutter PP260N ', '1 pc', 1, 0, 41, 537),
('PowerPac 3 Way 3M Extension Cord With 2-Pin Direct PP3883N', '3 Way 3M Extension Cord With 2-Pin Direct PP3883N ', '1 pc', 1, 0, 41, 537),
('PowerPac 3 Way Adapter With Switch & 2 Pin Direct PP8733', '3 Way Adapter With Switch & 2 Pin Direct PP8733 ', '1 Pc', 1, 0, 41, 537),
('PowerPac 3 Way Extension Cord 2M 2-Pin Direct PP7883-2', '3 Way Extension Cord 2M 2-Pin Direct PP7883-2 ', '1 Pc', 1, 0, 41, 537),
('PowerPac 4 Way 3M Extension Cord With 2-Pin Direct PP3884N', '4 Way 3M Extension Cord With 2-Pin Direct PP3884N ', '1 pc', 1, 0, 41, 537),
('PowerPac 4 Way 6M Extension Cord With 2-Pin Direct PP6884N', '4 Way 6M Extension Cord With 2-Pin Direct PP6884N ', '1 Pc', 1, 0, 41, 537),
('PowerPac 4 Way Extension Cord 2M 2-Pin Direct PP7884-2', '4 Way Extension Cord 2M 2-Pin Direct PP7884-2 ', '1 Pc', 1, 0, 41, 537),
('PowerPac 4 Way Extension Cord 2M With 2-Pin Direct', '4 Way Extension Cord 2M With 2-Pin Direct ', '1 pc', 1, 0, 41, 537),
('PowerPac 4 Way Extension Cord 3M 2-Pin Direct PP7884-3', '4 Way Extension Cord 3M 2-Pin Direct PP7884-3 ', '1 Pc', 1, 0, 41, 537),
('PowerPac 5 Way 3M Extension Cord With 2-Pin Direct PP3885N', '5 Way 3M Extension Cord With 2-Pin Direct PP3885N ', '1 pc', 1, 0, 41, 537),
('PowerPac 5 Way Extension Cord 2M 2-Pin Direct PP7885-2', '5 Way Extension Cord 2M 2-Pin Direct PP7885-2 ', '1 Pc', 1, 0, 41, 537),
('PowerPac 5 Way Extension Cord 2M With 2-Pin Direct PP3885-2', '5 Way Extension Cord 2M With 2-Pin Direct PP3885-2 ', '1 pc', 1, 0, 41, 537),
('PowerPac 6 Way Extension Cord 2M 2-Pin Direct PP7886-2', '6 Way Extension Cord 2M 2-Pin Direct PP7886-2 ', '1 Pc', 1, 0, 41, 537),
('PowerPac Extension Socket - 4 Way (PP468)', 'Extension Socket - 4 Way (PP468) ', '1 per pack', 1, 1, 41, 537),
('PowerPac Multi Adapter 2X USB PP010U', 'Multi Adapter 2X USB PP010U ', '1 pc', 1, 0, 41, 537),
('PowerPac Multi Travel Adapter 3x USB + 1 Type C Charger PP7980', 'Multi Travel Adapter 3x USB + 1 Type C Charger PP7980 ', '1 Pc', 1, 0, 41, 537),
('PowerPac Multi Travel Adapter With 2x USB Charger PP7971', 'Multi Travel Adapter With 2x USB Charger PP7971 ', '1 Pc', 1, 0, 41, 537),
('PowerPac Multi Travel Adapter With 2x USB Charger PP7972', 'Multi Travel Adapter With 2x USB Charger PP7972 ', '1 Pc', 1, 0, 41, 537),
('PowerPac Multi Travel Adapter With 2x USB Charger PP7973', 'Multi Travel Adapter With 2x USB Charger PP7973 ', '1 Pc', 1, 0, 41, 537),
('PowerPac Multi Travel Adapter With 2x USB Charger PP7977', 'Multi Travel Adapter With 2x USB Charger PP7977 ', '1 Pc', 1, 0, 41, 537),
('PowerPac Multi Travel Adapter With 4 USB Charger PP7981', 'Multi Travel Adapter With 4 USB Charger PP7981 ', '1 Pc', 1, 0, 41, 537),
('PowerPac Rechargeable LED Touch Light PP8028', 'Rechargeable LED Touch Light PP8028 ', '1 Pc', 1, 0, 41, 537),
('SILVERLITE Au-Nz-Cn Travel Adaptor', 'Au-Nz-Cn Travel Adaptor ', '1 PC', 1, 1, 42, 537),
('SILVERLITE Eu Travel Adaptor', 'Eu Travel Adaptor ', '1 PC', 1, 1, 42, 537),
('SILVERLITE International Travel Adaptor', 'International Travel Adaptor ', '1S', 1, 1, 42, 537),
('SUM 13AMP Socket Multi Plug', '13AMP Socket Multi Plug ', '1S', 1, 0, 43, 537),
('SUM 2 Outlets 3 Pin Portable Socket (3M)', '2 Outlets 3 Pin Portable Socket (3M) ', '1S', 1, 1, 43, 537),
('SUM 3 Outlets 3 Pin Portable Socket (3M)', '3 Outlets 3 Pin Portable Socket (3M) ', '1S', 1, 1, 43, 537),
('SUM 4 Outlets 3 Pin Portable Socket (3M)', '4 Outlets 3 Pin Portable Socket (3M) ', '1S', 1, 1, 43, 537),
('SUM 5 Outlets 3 Pin Portable Socket (3M)', '5 Outlets 3 Pin Portable Socket (3M) ', '1S', 1, 1, 43, 537),
('SUM Jolly 3 Way Multi Adaptor', 'Jolly 3 Way Multi Adaptor ', '1S', 1, 0, 43, 537),
('SUM Jolly UK Travel Adaptor', 'Jolly UK Travel Adaptor ', '1 PC', 1, 1, 43, 537),
('SUM Jolly US Travel Adapter', 'Jolly US Travel Adapter ', '1 PC', 1, 1, 43, 537),
('SUM Universal Travel Adapter (2 USB Ports)', 'Universal Travel Adapter (2 USB Ports) ', '1S', 1, 1, 43, 537),
('iMaxAlarm Portable Personal Alarm With Light (Matte Black)', 'Portable Personal Alarm With Light (Matte Black) ', '1S', 1, 1, 38, 526),
('iMaxAlarm Portable Personal Alarm With Light (Matte Grey)', 'Portable Personal Alarm With Light (Matte Grey) ', '1S', 1, 1, 38, 526),
('iMaxAlarm Portable Personal Alarm With Light (Matte Navy)', 'Portable Personal Alarm With Light (Matte Navy) ', '1S', 1, 1, 38, 526),
('iMaxAlarm Portable Personal Alarm With Light (Matte Rose)', 'Portable Personal Alarm With Light (Matte Rose) ', '1S', 1, 1, 38, 526),
('iMaxAlarm Portable Personal Alarm With Light (Matte Ruby)', 'Portable Personal Alarm With Light (Matte Ruby) ', '1S', 1, 1, 38, 526),
('iMaxAlarm Portable SOS Alert Personal Security Alarm (Black)', 'Portable SOS Alert Personal Security Alarm (Black) ', '1S', 1, 1, 38, 526),
('iMaxAlarm Portable SOS Alert Personal Security Alarm (Gold)', 'Portable SOS Alert Personal Security Alarm (Gold) ', '1S', 1, 1, 38, 526),
('iMaxAlarm Portable SOS Alert Personal Security Alarm (Gun Metal)', 'Portable SOS Alert Personal Security Alarm (Gun Metal) ', '1S', 1, 0, 38, 526),
('iMaxAlarm Portable SOS Alert Personal Security Alarm (Navy Blue)', 'Portable SOS Alert Personal Security Alarm (Navy Blue) ', '1S', 1, 1, 38, 526),
('iMaxAlarm Portable SOS Alert Personal Security Alarm (Rose Gold)', 'Portable SOS Alert Personal Security Alarm (Rose Gold) ', '1S', 1, 1, 38, 526),
('iMaxAlarm Portable SOS Alert Personal Security Alarm (White)', 'Portable SOS Alert Personal Security Alarm (White) ', '1S', 1, 1, 38, 526),
('PowerPac Mosquito Power Strike - S (PP2210)', 'Mosquito Power Strike - S (PP2210) ', '1 per pack', 1, 0, 41, 526),
('Chinatown Glutinous Rice Ball - Black Sesame ', 'Cold and refreshing, Glutinous Rice Ball - Black Sesame  , perfect for the hot Singaporean weather!', '300g', 1, 1, 44, 176),
('Coco Glace Tropical Coconut Dessert - Original', 'Cold and refreshing, Glace Tropical Coconut Dessert - Original , perfect for the hot Singaporean weather!', '220g', 1, 1, 45, 176),
('Kirei Kin Goma Golden Sesame Daifuku Mochi w Sesame RedBean-Frozen', 'Cold and refreshing, Kin Goma Golden Sesame Daifuku Mochi w Sesame RedBean-Frozen , perfect for the hot Singaporean weather!', '90G', 1, 0, 46, 176),
('Kirei Sakura Mochi Japanese Dessert - Frozen', 'Cold and refreshing, Sakura Mochi Japanese Dessert - Frozen , perfect for the hot Singaporean weather!', '80G', 1, 0, 46, 176),
('Mummys Kajukatli', 'Cold and refreshing, Kajukatli , perfect for the hot Singaporean weather!', '400g', 1, 0, 47, 176),
('Rachel''s Organic Twin Traditional Creamy Rice Pudding Twinpack', 'Cold and refreshing, Organic Twin Traditional Creamy Rice Pudding Twinpack , perfect for the hot Singaporean weather!', '300G', 1, 1, 48, 176),
('Hokkaido Gateaux Au Chocolat Cheese Cake - Frozen', 'Fluffy and cool! Gateaux Au Chocolat Cheese Cake - Frozen ', '270G', 1, 0, 46, 177),
('Kirei Hokkaido Brulee Cheese Cake - Frozen', 'Fluffy and cool! Hokkaido Brulee Cheese Cake - Frozen ', '270G', 1, 0, 46, 177),
('Kirei Hokkaido New York Cheese Cake - Frozen', 'Fluffy and cool! Hokkaido New York Cheese Cake - Frozen ', '240G', 1, 0, 46, 177),
('Silly Yaks Cocktail Muffin: Orange (Frozen)', 'Fluffy and cool! Yaks Cocktail Muffin: Orange (Frozen) ', '4 x 40g', 1, 0, 50, 177),
('Silly Yaks White Chocolate and Raspberry Muffin (Frozen)', 'Fluffy and cool! Yaks White Chocolate and Raspberry Muffin (Frozen) ', '4 x 75g', 1, 1, 50, 177),
('Sara Lee Frozen Pound Cake - All Purpose (Plain)', 'Fluffy and cool! Lee Frozen Pound Cake - All Purpose (Plain) ', '300g', 1, 0, 51, 177),
('Sara Lee Frozen Pound Cake - Chocolate', 'Fluffy and cool! Lee Frozen Pound Cake - Chocolate ', '300g', 1, 0, 51, 177),
('Sara Lee Frozen Pound Cake - Chocolate Swirl', 'Fluffy and cool! Lee Frozen Pound Cake - Chocolate Swirl ', '300g', 1, 0, 51, 177),
('Silly Yaks Chocolate Mud Muffin (Frozen)', 'Fluffy and cool! Yaks Chocolate Mud Muffin (Frozen) ', '4 x 75g', 1, 0, 50, 177),
('Silly Yaks Cocktail Muffin: White Chocolate And Raspberry(Frozen)', 'Fluffy and cool! Yaks Cocktail Muffin: White Chocolate And Raspberry(Frozen) ', '4 x 40g', 1, 1, 50, 177),
('Silly Yaks Orange Muffin (Frozen)', 'Fluffy and cool! Yaks Orange Muffin (Frozen) ', '4 x 75g', 1, 1, 50, 177),
('Tesco Frozen Cheesecake - New York', 'Fluffy and cool! Frozen Cheesecake - New York ', '450g', 1, 1, 29, 177),
('Tesco Frozen Raspberries', 'Stay fresh for longer!, Frozen Raspberries ', '350g', 1, 1, 29, 178),
('ANNO IMO Japanese Roasted Sweet Potato - Frozen (S Size)', 'Easy and practical! IMO Japanese Roasted Sweet Potato - Frozen (S Size) ', '500G', 1, 0, 52, 179),
('CB Mixed Vegetables', 'Easy and practical! Mixed Vegetables ', '1000G', 1, 1, 53, 179),
('CB Sweet Corn', 'Easy and practical! Sweet Corn ', 'Halal', 1, 1, 53, 179),
('Emborg Frozen Sweet Corn', 'Easy and practical! Frozen Sweet Corn ', '1000G', 1, 1, 54, 179),
('FairPrice Frozen Edamame Salted Soy Beans', 'Easy and practical! Frozen Edamame Salted Soy Beans ', 'Halal', 1, 1, 12, 179),
('FairPrice Frozen Fresh Garden Peas', 'Easy and practical! Frozen Fresh Garden Peas ', '450g', 1, 1, 12, 179),
('Kirei Kamakurayama Kotsububachi Japanese Natto Set - Frozen', 'Easy and practical! Kamakurayama Kotsububachi Japanese Natto Set - Frozen ', '500g', 1, 0, 46, 179),
('Kirei Kamakurayama Kuromame Natto Pack -Frozen', 'Easy and practical! Kamakurayama Kuromame Natto Pack -Frozen ', '400g', 1, 0, 46, 179),
('Kirei Kamakurayama Nihon No Ohtsubu Japanese Natto - Frozen', 'Easy and practical! Kamakurayama Nihon No Ohtsubu Japanese Natto - Frozen ', '80G', 1, 0, 46, 179),
('Kinjirushi Nama Wasabi (Fresh Grated Wasabi) - Frozen', 'Easy and practical! Nama Wasabi (Fresh Grated Wasabi) - Frozen ', '80G', 1, 0, 56, 179),
('ANNO IMO Japanese Roasted Sweet Potato - Frozen (M Size)', 'Easy and practical! IMO Japanese Roasted Sweet Potato - Frozen (M Size) ', '80G', 1, 0, 53, 179),
('Kirei CHUKKADON NO GU Japanese Chap Chye', 'Easy and practical! CHUKKADON NO GU Japanese Chap Chye ', '200G', 1, 0, 46, 179),
('Kirei Edamame - Frozen', 'Easy and practical! Edamame - Frozen ', '500G', 1, 0, 46, 179),
('Kirei Edamame Seed Frozen by Kirei Japanese Food', 'Easy and practical! Edamame Seed Frozen by Kirei Japanese Food ', '400G', 1, 0, 46, 179),
('Watties Frozen Mixed Veges', 'Easy and practical! Frozen Mixed Veges ', '500g', 1, 1, 57, 179);
